apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus-uid
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: false

  - name: Jaeger
    type: jaeger
    uid: jaeger-uid
    url: http://jaeger:16686
    access: proxy
    editable: false

  - name: Loki
    type: loki
    uid: loki-uid
    url: http://loki:3100
    access: proxy
    editable: false
    jsonData:
      derivedFields:
        - matcherRegex: 'TraceId=([a-f0-9]+)'
          name: TraceID
          url: '${__value.raw}'
          datasourceUid: jaeger-uid
          urlDisplayLabel: Ver en Jaeger
